file_format: "1"
id: sofle_choc
name: SofleChoc
type: shield
url: https://github.com/josefadamcik/SofleKeyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - sofle_choc_left
  - sofle_choc_right
